name: Build snapshot
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare pacman keyring
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring base-devel fakeroot dos2unix wget $(grep makedepends PKGBUILD | cut -d '=' -f 2 | sed 's/(//g' | sed 's/)//g' |tr -d \'\")
          find . -type f -print0 | xargs -0 dos2unix
          chown -R nobody:nobody .
          
      - name: Build Arch package
        run: |
          su -s /bin/bash nobody -c "makepkg -s --nodeps && mkdir pkgout && mv *.tar.zst pkgout"

      - name: Set current package distribution variables
        run: |
          echo "PKGNAME=$(grep pkgname PKGBUILD | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "VER=$(grep pkgname PKGBUILD | cut -d "=" -f 2)-snapshot$(date +%Y%m%d.%H%M)-1-x86_64_CI" >> $GITHUB_ENV
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VER }}
          path: pkg/${{ env.PKGNAME }}/*
